Add more meaningful output after the password is generated

diff --git a/bin/generate_kms_password b/bin/generate_kms_password
--- a/bin/generate_kms_password
+++ b/bin/generate_kms_password
@@ -46,3 +46,11 @@ encrypt password.plain_text $encryption_context $key
 decrypt password.plain_text.encrypted_base64 $encryption_context > password.plain_text.validation
 
 diff password.plain_text password.plain_text.validation
+
+if [ $? -ne 0 ]; then
+  echo "ERROR: Failed to validate the encrypted password - when it was decrypted, it did not match."
+  exit 1
+else
+  echo "The plaintext password is in password.plain_text - do not share this file or its contents"
+  echo "The encrypted, base64-encoded, password can be found in password.plain_text.encrypted_base64"
+fi
